apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: attach-role-with-user
  namespace: default
subjects:
- kind: User
  name: suraj
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role    
  name: myrole
  apiGroup: rbac.authorization.k8s.io